---
app_config:
  
  #This is the default url of your site, this allows
  #sPHPf switch pages in the {{path}} var correctly
  default_uri: http://yoursite/sPHPf/
  
  #This setting 1/0 is to set the production mode or not.
  production: 0
  
  #This setting is used to load the error view (production: 0)
  error: errors/application.twig
  
  #This setting is used to load the error in production environment (production: 1)
  error_production: errors/production.twig